### ISSUE TITLE
Error decoding JobData when dequeuing job

### ISSUE THREAD

**Issue by bottlehall** [m-barthelemy/vapor-queues-fluent-driver#21] opened 2022-02-11 20:27 UTC
JobModel's data property is Data, but the JobData instance is encoded as a JSON array. On decoding, this causes an error saying Data expected but Array found.

In JobModel.swift:
1. Change the data property's type to JobData on line 42.
2. Change the assignment on line 62 to self.data = data.

In FluentQueue.swift:
1. Change line 21 to return job.data.

**Comment by m-barthelemy** [comment] 2022-02-12 08:00
Hi, thanks for the report. Looks similar to #20

I haven't had any time to look into it but will do (hopefully) very soon. But if you feel like making a PR please go ahead!

**Comment by bottlehall** [comment] 2022-02-12 11:38
Created PR.

**Comment by m-barthelemy** [comment] 2022-02-20 10:49
Thanks a lot for the PR!
Released https://github.com/m-barthelemy/vapor-queues-fluent-driver/releases/tag/2.0.0

**Comment by bottlehall** [comment] 2022-08-06 08:24
Any chance of getting this implemented into the default release? I've just built a new system from scratch and had to go in and put the changes in by hand yet again!

**Comment by m-barthelemy** [comment] 2022-08-06 08:53
My latest investigations (a few of months ago) showed that:
- I can reproduce the issue with Mysql
- I cannot reproduce the issue with Postgres
- if I remember correctly, the fix you proposed broke with Postgres

Do you confirm that you are experiencing this issue when using Mysql?

**Comment by bottlehall** [comment] 2022-08-06 09:01
Yes. I only use MySQL.

**Comment by m-barthelemy** [comment] 2022-09-04 03:54
Should (hopefully) be fixed in [3.0.0-beta1](https://github.com/m-barthelemy/vapor-queues-fluent-driver/releases/tag/3.0.0-beta1)

Feel free to reopen an issue if you're still having trouble with the new releases.

**Closed by m-barthelemy** 2022-09-04 03:54 UTC
